# Form implementation generated from reading ui file 'f:\UNI_STUFF\5th Sem\Photo-Wizard\ui_files\crop_toolbar.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_edit_toolbar(object):
    def setupUi(self, edit_toolbar):
        edit_toolbar.setObjectName("edit_toolbar")
        edit_toolbar.resize(1003, 589)
        self.gridLayout = QtWidgets.QGridLayout(edit_toolbar)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.main_widget = QtWidgets.QWidget(parent=edit_toolbar)
        self.main_widget.setObjectName("main_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_widget)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.mirror_lr_button = QtWidgets.QPushButton(parent=self.main_widget)
        self.mirror_lr_button.setObjectName("mirror_lr_button")
        self.horizontalLayout.addWidget(self.mirror_lr_button)
        self.mirror_ud_button = QtWidgets.QPushButton(parent=self.main_widget)
        self.mirror_ud_button.setObjectName("mirror_ud_button")
        self.horizontalLayout.addWidget(self.mirror_ud_button)
        self.rotate_button = QtWidgets.QPushButton(parent=self.main_widget)
        self.rotate_button.setObjectName("rotate_button")
        self.horizontalLayout.addWidget(self.rotate_button)
        self.save_button = QtWidgets.QPushButton(parent=self.main_widget)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.cancel_button = QtWidgets.QPushButton(parent=self.main_widget)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.main_widget, 0, 0, 1, 1)

        self.retranslateUi(edit_toolbar)
        QtCore.QMetaObject.connectSlotsByName(edit_toolbar)

    def retranslateUi(self, edit_toolbar):
        _translate = QtCore.QCoreApplication.translate
        edit_toolbar.setWindowTitle(_translate("edit_toolbar", "Form"))
        self.mirror_lr_button.setText(_translate("edit_toolbar", "Mirror Left-Right"))
        self.mirror_ud_button.setText(_translate("edit_toolbar", "Mirror Up-Down"))
        self.rotate_button.setText(_translate("edit_toolbar", "Rotate "))
        self.save_button.setText(_translate("edit_toolbar", "Save"))
        self.cancel_button.setText(_translate("edit_toolbar", "Cancel"))
