# Form implementation generated from reading ui file 'f:\UNI_STUFF\5th Sem\Photo-Wizard\ui_files\edit_toolbar.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_edit_toolbar(object):
    def setupUi(self, edit_toolbar):
        edit_toolbar.setObjectName("edit_toolbar")
        edit_toolbar.resize(1003, 589)
        self.gridLayout = QtWidgets.QGridLayout(edit_toolbar)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.main_widget = QtWidgets.QWidget(parent=edit_toolbar)
        self.main_widget.setObjectName("main_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_widget)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.crop_button = QtWidgets.QPushButton(parent=self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crop_button.sizePolicy().hasHeightForWidth())
        self.crop_button.setSizePolicy(sizePolicy)
        self.crop_button.setObjectName("crop_button")
        self.horizontalLayout.addWidget(self.crop_button)
        self.adjustment_button = QtWidgets.QPushButton(parent=self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adjustment_button.sizePolicy().hasHeightForWidth())
        self.adjustment_button.setSizePolicy(sizePolicy)
        self.adjustment_button.setObjectName("adjustment_button")
        self.horizontalLayout.addWidget(self.adjustment_button)
        self.filter_button = QtWidgets.QPushButton(parent=self.main_widget)
        self.filter_button.setObjectName("filter_button")
        self.horizontalLayout.addWidget(self.filter_button)
        self.doodle_button = QtWidgets.QPushButton(parent=self.main_widget)
        self.doodle_button.setObjectName("doodle_button")
        self.horizontalLayout.addWidget(self.doodle_button)
        self.save_button = QtWidgets.QPushButton(parent=self.main_widget)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.cancel_button = QtWidgets.QPushButton(parent=self.main_widget)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.main_widget, 0, 0, 1, 1)

        self.retranslateUi(edit_toolbar)
        QtCore.QMetaObject.connectSlotsByName(edit_toolbar)

    def retranslateUi(self, edit_toolbar):
        _translate = QtCore.QCoreApplication.translate
        edit_toolbar.setWindowTitle(_translate("edit_toolbar", "Form"))
        self.crop_button.setText(_translate("edit_toolbar", "Crop"))
        self.adjustment_button.setText(_translate("edit_toolbar", "Adjustment"))
        self.filter_button.setText(_translate("edit_toolbar", "Filter"))
        self.doodle_button.setText(_translate("edit_toolbar", "Doodle"))
        self.save_button.setText(_translate("edit_toolbar", "Save"))
        self.cancel_button.setText(_translate("edit_toolbar", "Cancel"))
